var students;
students = [];
var obj;
obj = { studentName: 'fahim', id: 232324 };
var classStudent;
classStudent = { studentName: 'Hamid', id: 8878, isAttendance: true };
var student1;
student1 = { studentName: 'Galib', id: 9000, isAttendance: false };
students.push(student1);
console.log(students);
console.log(classStudent);
console.log(classStudent.studentName);
console.log(classStudent['id']);
console.log(obj);
console.log(obj['id']);
